/* Action types */
export const actionTypes = {
  WEATHER_CHANGE_SEARCH_TEXT: 'WEATHER/CHANGE_SEARCH_TEXT',
  WEATHER_FETCH: 'WEATHER/WEATHER_FETCH',
  WEATHER_FETCH_SUCCESS: 'WEATHER/WEATHER_FETCH_SUCCESS',
  WEATHER_FETCH_FAIL: 'WEATHER/WEATHER_FETCH_SUCCESS_FAIL'
}
